title: Zixuan He's Homepage
page-top-title: Zixuan He
top-section-bg-text: Ph.D Biological and Agricultural Engineering
home-subtitle: Zixuan He&ensp;|&ensp;何子玄
copyright-text: '&copy; Zixuan He 2023-2025. All Rights Reserved.'
